from flask import Flask, render_template, request, send_file
import agents
from reportlab.pdfgen import canvas

app = Flask(__name__)


@app.route("/")
def home():
    return render_template("home.html")


@app.route("/input")
def input_page():
    return render_template("input.html")


@app.route("/predict", methods=["POST"])
def predict():

    premium = int(request.form["premium"])
    accidents = int(request.form["accidents"])
    age = int(request.form["age"])
    miles = int(request.form["miles"])

    risk = agents.risk_profiler(accidents)
    conversion = agents.conversion_predictor()
    advice = agents.premium_advisor(premium)
    decision = agents.decision_router(risk, conversion)

    return render_template(
        "result.html",
        risk=risk,
        conversion=conversion,
        advice=advice,
        decision=decision
    )


@app.route("/download")
def download():

    file = "report.pdf"

    c = canvas.Canvas(file)

    c.setFont("Helvetica-Bold",20)
    c.drawString(100,750,"AI Insurance Evaluation Report")

    c.setFont("Helvetica",12)

    c.drawString(100,700,"Generated by Autonomous Quote Agent System")

    c.drawString(100,650,"This report summarizes the AI agent evaluation results.")

    c.save()

    return send_file(file, as_attachment=True)


if __name__ == "__main__":
    app.run()
